=== mormegil-cz/gnubg/met/met.dtd
<!--

     met.dtd

     by Joern Thyssen <jthyssen@dk.ibm.com>, 2002

     This program is free software; you can redistribute it and/or modify
     it under the terms of version 3 or later of the GNU General Public License as
     published by the Free Software Foundation.
     
     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.
     
     You should have received a copy of the GNU General Public License
     along with this program; if not, write to the Free Software
     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


     $Id$

 -->


<!ELEMENT met (info,pre-crawford-table,post-crawford-table+)>

<!ELEMENT info (name,description,length)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT length (#PCDATA)>

<!ELEMENT pre-crawford-table (row*|parameters)>
<!ATTLIST pre-crawford-table type CDATA #IMPLIED>

<!ELEMENT post-crawford-table (row|parameters)>
<!ATTLIST post-crawford-table type CDATA #IMPLIED
                             player CDATA #IMPLIED>

<!ELEMENT row (me)*>

<!ELEMENT me (#PCDATA)>

<!ELEMENT parameters (parameter*)>
<!ELEMENT parameter (#PCDATA)>
<!ATTLIST parameter name CDATA #REQUIRED>

=== mormegil-cz/gnubg/met/zadeh.xml
<?xml version = "1.0"?>
<!DOCTYPE met SYSTEM "met.dtd">

<!--

     zadeh.xml

     by Joern Thyssen <jthyssen@dk.ibm.com>, 2002

     This program is free software; you can redistribute it and/or modify
     it under the terms of version 2 of the GNU General Public License as
     published by the Free Software Foundation.

     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with this program; if not, write to the Free Software
      Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

     $Id$

 -->


<met>
   <info>
      <name>N. Zadeh</name>
      <description>N. Zadeh, Management Science 23, 986 (1977)</description>
      <length>-1</length>
   </info>

   <pre-crawford-table type="zadeh">

      <parameters>
         <parameter name="gammon-rate-leader">0.25</parameter>
         <parameter name="gammon-rate-trailer">0.15</parameter>
         <parameter name="delta">0.08</parameter>
         <parameter name="delta-bar">0.06</parameter>
      </parameters>

   </pre-crawford-table>      
 

   <post-crawford-table type="zadeh">

      <parameters>
         <parameter name="gammon-rate-trailer">0.25</parameter>
         <parameter name="free-drop-2-away">0.015</parameter>
         <parameter name="free-drop-4-away">0.004</parameter>
      </parameters>

   </post-crawford-table>   

</met>

=== mormegil-cz/gnubg/met/Kazaross-Shaw.xml
<?xml version = "1.0"?>
<!DOCTYPE met PUBLIC "-//GNU Backgammon//DTD Match Equity Tables//EN"
                     "met.dtd">

<!--

     Kazaross-Shaw.xml

     by Øystein Johansen <oystein@gnubg.org>, 2003


     This file is distributed as a part of the GNU Backgammon program.

     Copying and distribution of verbatim and modified versions of this file
     is permitted in any medium provided the copyright notice and this
     permission notice are preserved.

     This match equity table is based rollouts by GNU Backgammon. It's still
     work in progress.

     $Id$

 -->


<met>
  <info>
    <name>Kazaross and Shaw</name>
    <description>Neil Kazaross, Ian Shaw and GNU Backgammon, Table based on GNU Backgammon rollouts.</description>
    <length>2</length>
  </info>

  <pre-crawford-table type="explicit">

    <row>
      <me>0.500</me>
      <me>0.682</me>
    </row>

    <row>
      <me>0.318</me>
      <me>0.500</me>
    </row>

  </pre-crawford-table>      
  

  <post-crawford-table type="explicit" player="both">

    <row>
      <me>0.50</me>
      <me>0.485</me>
    </row>

  </post-crawford-table>   

</met>
